config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  resources :home, only: :index

  post :send_message, to: 'home#send_message'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :load_message_form

  def index; end

  def send_message
    ContactMailer.client_question(@form).deliver
  end

  private

  def load_message_form
    @form = MessageForm.new(params[:form_data])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def site_name
    A9n.site_name
  end

  def copyright
    I18n.t(:copyright, scope: 'footer', year: Date.today.year).html_safe
  end

  def facebook_url
    A9n.facebook_url
  end

  def twitter_url
    A9n.twitter_url
  end

  def linkedin_url
    A9n.linkedin_url
  end

  def gravatar_url
    A9n.gravatar_url
  end
end

app/views/home/_contact.html.erb
<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Contact</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <%= form_for(@form, as: :form_data, url: send_message_path, html: { name: "sentMessage", id: "contactForm", novalidate: true}) do |form| %>
        <form name="sentMessage" id="contactForm" novalidate>
          <div class="row">


            <div class="col-md-offset-3 col-md-6">
              <div class="form-group">
                <%= form.email_field :email, placeholder: "Your Email *", class: "form-control", id: "email", data: { :'validation-required-message' => "Please enter your email address.", required: true } %>
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <%= form.text_area :message, placeholder: "Your Message *", class: "form-control", id: "message", data: { :'validation-required-message' => "Please enter a message.", required: true } %>
                <p class="help-block text-danger"></p>
              </div>
            </div>

            <div class="clearfix"></div>
            <div class="col-lg-12 text-center">
              <div id="success"></div>
              <%= form.button "Send Message", class: "btn btn-xl2" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/home/_header.html.erb
<header>
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in">Welcome To Software House!</div>
      <div class="intro-heading">It's Nice To Meet You</div>
      <a href="#portfolio" class="page-scroll btn btn-xl2">More info.</a>
    </div>
  </div>
</header>

app/views/home/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header page-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand page-scroll" href="#page-top">damianO śliwecki</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li>
          <a class="page-scroll" href="#portfolio">Portfolio</a>
        </li>
        <li>
          <a class="page-scroll" href="#services">Technologies</a>
        </li>
        <li>
          <a class="page-scroll" href="#team">Me</a>
        </li>
        <li>
          <a class="page-scroll" href="#contact">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/_portfolio.html.erb
<section id="portfolio">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Portfolio</h2>
        <h3 class="section-subheading text-muted">I will write modern applications or websites for You.</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 col-sm-6 portfolio-item">
          <a href="http://37.233.101.76" class="portfolio-link" data-toggle="modal" target='_blank'>
              <div class="portfolio-hover">
                  <div class="portfolio-hover-content">
                      <i class="fa fa-plus fa-3x"></i>
                  </div>
              </div>
              <%= image_tag('portfolio/wyrzucto.png', class: "img-responsive") %>
          </a>
          <div class="portfolio-caption">
              <h4>Wyrzuć.to</h4>
              <p class="text-muted">Implemented backend (Ruby On Rails · jQuery · Google Maps · Sidekiq)</p>
          </div>
      </div>

      <div class="col-md-6 col-sm-6 portfolio-item">
          <a href="http://posterro.com" class="portfolio-link" data-toggle="modal" target='_blank'>
              <div class="portfolio-hover">
                  <div class="portfolio-hover-content">
                      <i class="fa fa-plus fa-3x"></i>
                  </div>
              </div>
              <%= image_tag('portfolio/posterro.png', class: "img-responsive") %>
          </a>
          <div class="portfolio-caption">
              <h4>Posterro</h4>
              <p class="text-muted">
                Refactored old code, upgraded Ruby On Rails from 3.0 to 4.2 and transferred to www.digitalocean.com server
              </p>
          </div>
      </div>

      <div class="col-md-6 col-sm-6 portfolio-item">
          <a href="http://www.hipermarket3d.pl" class="portfolio-link" data-toggle="modal" target='_blank'>
              <div class="portfolio-hover">
                  <div class="portfolio-hover-content">
                      <i class="fa fa-plus fa-3x"></i>
                  </div>
              </div>
              <%= image_tag('portfolio/hipermarket3d.png', class: "img-responsive") %>
          </a>
          <div class="portfolio-caption">
              <h4>Hipermarket3d</h4>
              <p class="text-muted">Member of developers team. Repaired bugs and implemented new features</p>
          </div>
      </div>

      <div class="col-md-6 col-sm-6 portfolio-item">
          <a href="http://infakt.pl" class="portfolio-link" data-toggle="modal" target='_blank'>
              <div class="portfolio-hover">
                  <div class="portfolio-hover-content">
                      <i class="fa fa-plus fa-3x"></i>
                  </div>
              </div>
              <%= image_tag('portfolio/infakt.png', class: "img-responsive") %>
          </a>
          <div class="portfolio-caption">
              <h4>Infakt</h4>
              <p class="text-muted">Member of developers team. Repaired bugs and implemented new features</p>
          </div>
      </div>
    </div>
  </div>
</section>

app/views/home/_services.html.erb
<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Technologies</h2>
        <h3 class="section-subheading text-muted"><!-- What technologies I use. --></h3>
      </div>
    </div>

    <div class="row text-center">
      <div class="col-md-2 col-lg-2 col-lg-offset-2 col-md-offset-2 col-sm-offset-2">
        <div class="hex" id='angularjs-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
      <div class="col-md-2 col-lg-2">
        <div class="hex" id='css3-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
      <div class="col-md-2 col-lg-2">
        <div class="hex" id='elasticsearch-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
      <div class="col-md-2 col-lg-2">
        <div class="hex" id='github-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
    </div>

    <div class="row text-center">
      <div class="col-md-2 col-lg-2 col-lg-offset-3 col-md-offset-3 col-sm-offset-3">
        <div class="hex" id='haml-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
      <div class="col-md-2 col-lg-2">
        <div class="hex" id='html5-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
      <div class="col-md-2 col-lg-2">
        <div class="hex" id='java-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
    </div>

    <div class="row text-center">
      <div class="col-md-2 col-lg-2 col-lg-offset-2 col-md-offset-2 col-sm-offset-2">
        <div class="hex" id='javascript-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
      <div class="col-md-2 col-lg-2">
        <div class="hex" id='jquery-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
      <div class="col-md-2 col-lg-2">
        <div class="hex" id='mongodb-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
      <div class="col-md-2 col-lg-2">
        <div class="hex" id='nodejs-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
    </div>

    <div class="row text-center">
      <div class="col-md-2 col-lg-2 col-lg-offset-3 col-md-offset-3 col-sm-offset-3">
        <div class="hex" id='postgresql-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
      <div class="col-md-2 col-lg-2">
        <div class="hex" id='redis-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
      <div class="col-md-2 col-lg-2">
        <div class="hex" id='ruby-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
    </div>

    <div class="row text-center">
      <div class="col-md-2 col-lg-2 col-lg-offset-2 col-md-offset-2 col-sm-offset-2">
        <div class="hex" id='rubyonrails-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
      <div class="col-md-2 col-lg-2">
        <div class="hex" id='sass-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
      <div class="col-md-2 col-lg-2">
        <div class="hex" id='sidekiq-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
      <div class="col-md-2 col-lg-2">
        <div class="hex" id='sql-image'>
          <!-- <a href="#"></a> -->
          <div class="corner-1"></div>
          <div class="corner-2"></div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/_team.html.erb
<section id="team">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">It's me</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4">
      </div>
      <div class="col-sm-4">
        <div class="team-member">
          <%= image_tag('author.png', class: "img-responsive img-circle", size: '280x280') %>
          <h4>Damian Śliwecki</h4>
          <p class="text-muted">Full stack developer</p>
          <ul class="list-inline social-buttons">
            <li>
              <%= link_to(twitter_url, target: 'blank') do %>
                <i class="fa fa-twitter"></i>
              <% end %>
            </li>
            <li>
              <%= link_to(facebook_url, target: 'blank') do %>
                <i class="fa fa-facebook"></i>
              <% end %>
            </li>
            <li>
              <%= link_to(linkedin_url, target: 'blank') do %>
                <i class="fa fa-linkedin"></i>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<%= render 'navigation' %>
<%= render 'header' %>
<%= render 'portfolio' %>
<%= render 'services' %>
<%= render 'team' %>
<%= render 'contact' %>

app/views/home/send_message.js.erb
<% if @form.valid? %>
  $('#success').html("<div class='alert alert-success'>");
  $('#success > .alert-success').html("<button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;").append("</button>");
  $('#success > .alert-success').append("<strong>Your message has been sent. </strong>");
  $('#success > .alert-success').append('</div>');
  $('#contactForm').trigger("reset");
<% else %>
  $('#success').html("<div class='alert alert-danger'>");
  $('#success > .alert-danger').html("<button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;").append("</button>");
  $('#success > .alert-danger').append("<strong>Sorry, it seems that my mail server is not responding. Please try again later!");
  $('#success > .alert-danger').append('</div>');
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <span class="copyright"><%= copyright %></span>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= site_name %></title>
    <link rel="icon" type="image/x-icon" href="<%= gravatar_url %>"/>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="canonical" href="http://www.sliwecki.pl" />
    <meta property="og:locale" content="pl_PL" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Damian Śliwecki - Portfolio" />
    <meta property="og:description" content="Damian Śliwecki - Portfolio. I create modern web application and web site for You" />
    <meta property="og:url" content="http://www.sliwecki.pl" />
    <meta property="og:image" content="<%= gravatar_url %>" />
    <link rel="alternate" hreflang="pl" href="http://www.sliwecki.pl">
    <link rel="alternate" hreflang="en" href="http://www.sliwecki.pl">
    <meta name="description" content="Endorfina soft Damian Śliwecki. I create modern web application and web site for You">
    <meta name="author" content="Damian Śliwecki">
    <meta name="title" content="Damian Śliwecki - Portfolio - Endorfina soft">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.javascripts/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body id="page-top" class="index">
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>